# Generated by Django 4.2.7 on 2023-11-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusterEmploymentES21', '0003_coords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coords',
            new_name='coordsOfPic',
        ),
    ]
