# Generated by Django 4.2.7 on 2023-11-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusterEmploymentES21', '0004_rename_coords_coordsofpic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coordsOfPic',
            new_name='coordsOfHydrogen',
        ),
    ]
