# Generated by Django 4.2.7 on 2023-11-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusterEmploymentES21', '0005_rename_coordsofpic_coordsofhydrogen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coordsOfHydrogen',
            new_name='hydrogenPlaces',
        ),
    ]
