# Generated by Django 4.2.7 on 2023-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterEmploymentES21', '0007_carbonplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='sulfurPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=10)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
    ]
